export const viewer = {
  id: 'alex',
  name: 'Alex',
  fullName: 'Alex Mercer',
  age: 31,
  plan: 'Premium',
  city: 'Brussels',
  email: 'you@matchpulse.com',
  phone: '',
  language: 'English',
  photo: '/portraits/alex.jpg',
  orientation: 'Straight',
  genderIdentity: 'Man',
  interestedIn: 'Everyone',
  photoPrivacy: 'public',
  lookingFor: 'Serious',
  bio: 'Warm, ambitious, direct. I like city energy, quiet mornings, and dates that feel natural instead of performed.',
  profileCompletion: 98,
  preferences: {
    values: ['Consistency', 'Emotional availability', 'Growth', 'Creative life'],
    dealbreakers: ['Vague intent', 'Poor communication', 'No curiosity'],
    visualTaste: ['Natural style', 'Warm eyes', 'Quiet confidence'],
    dateRhythm: ['Coffee first', 'Walks', 'Dinner after trust'],
  },
  aiMemory: [
    'You value honesty, consistency and ambition.',
    'You prefer deep conversations and real connection over small talk.',
    'You are most attracted to emotionally intelligent people with a creative side.',
    'You enjoy active lifestyles and spontaneous adventures.',
  ],
}

export const matches = [
  {
    id: 'julian',
    name: 'Julian',
    age: 28,
    role: 'Architect at Studio A',
    city: 'Brussels',
    distance: '2.4 km away',
    status: 'Online now',
    intent: ['Serious', 'Tonight', 'Values aligned'],
    score: 93,
    photo: '/portraits/marco.jpg',
    portrait: '/portraits/marco.jpg',
    genderIdentity: 'Man',
    interestedIn: 'Everyone',
    photoPrivacy: 'public',
    about:
      'Designs quiet spaces, cooks late, and likes dates that turn into long walks.',
    shared: [
      'You both value calm chemistry and clear communication.',
      'You both like architecture, slow travel and dinner places with atmosphere.',
      'You both want something serious, but without forcing the timeline.',
    ],
    metrics: {
      Values: 93,
      Attraction: 91,
      Lifestyle: 88,
      Intent: 90,
      Uncertainty: 7,
    },
    map: { x: 50, y: 44 },
  },
  {
    id: 'marco',
    name: 'Marco',
    age: 31,
    role: 'Product Designer',
    city: 'Brussels',
    distance: '4.1 km away',
    status: 'Online now',
    intent: ['Serious', 'Casual'],
    score: 89,
    photo: '/portraits/ethan.jpg',
    portrait: '/portraits/ethan.jpg',
    genderIdentity: 'Man',
    interestedIn: 'Men',
    photoPrivacy: 'blurred',
    about:
      'Soft-spoken, visually sharp, and very good at finding a table near the window.',
    shared: [
      'You both care about good taste without showing off.',
      'You share a preference for slow starts and thoughtful messages.',
      'Your date rhythms are compatible: short first date, no pressure.',
    ],
    metrics: {
      Values: 88,
      Attraction: 89,
      Lifestyle: 85,
      Intent: 86,
      Uncertainty: 14,
    },
    map: { x: 75, y: 30 },
  },
  {
    id: 'ethan',
    name: 'Ethan',
    age: 26,
    role: 'Entrepreneur',
    city: 'Brussels',
    distance: '1.8 km away',
    status: 'Online now',
    intent: ['Serious', 'Tonight'],
    score: 87,
    photo: '/portraits/julian.jpg',
    portrait: '/portraits/julian.jpg',
    genderIdentity: 'Man',
    interestedIn: 'Everyone',
    photoPrivacy: 'private',
    about:
      'Building a small company and looking for someone who understands momentum.',
    shared: [
      'You both value growth and meaningful connection.',
      'You share interest in soulful conversations and travel.',
      'There is high attraction, but more uncertainty around pace.',
    ],
    metrics: {
      Values: 90,
      Attraction: 92,
      Lifestyle: 82,
      Intent: 84,
      Uncertainty: 18,
    },
    map: { x: 28, y: 63 },
  },
  {
    id: 'noah',
    name: 'Noah',
    age: 29,
    role: 'Data Scientist',
    city: 'Brussels',
    distance: '3.2 km away',
    status: 'Online now',
    intent: ['Serious', 'Casual'],
    score: 84,
    photo: '/portraits/noah.jpg',
    portrait: '/portraits/noah.jpg',
    genderIdentity: 'Man',
    interestedIn: 'Men & women',
    photoPrivacy: 'public',
    about:
      'Curious, grounded, into long bike rides and cleanly written thoughts.',
    shared: [
      'You both enjoy precision and emotionally safe conversations.',
      'You share a calm social style and similar weekend rhythm.',
      'The AI sees less obvious spark, but strong long-term stability.',
    ],
    metrics: {
      Values: 86,
      Attraction: 79,
      Lifestyle: 91,
      Intent: 87,
      Uncertainty: 12,
    },
    map: { x: 64, y: 75 },
  },
  {
    id: 'liam',
    name: 'Liam',
    age: 27,
    role: 'Brand Strategist',
    city: 'Brussels',
    distance: '5.5 km away',
    status: 'Online now',
    intent: ['Casual', 'Tonight'],
    score: 81,
    photo: '/portraits/liam.jpg',
    portrait: '/portraits/liam.jpg',
    genderIdentity: 'Non-binary',
    interestedIn: 'Everyone',
    photoPrivacy: 'public',
    about:
      'Fast humor, big energy, and open to a fun plan when the vibe is honest.',
    shared: [
      'You both like spontaneous evenings and city energy.',
      'The attraction signal is high, but intent alignment is lower.',
      'Better as a playful or low-pressure match.',
    ],
    metrics: {
      Values: 75,
      Attraction: 90,
      Lifestyle: 84,
      Intent: 68,
      Uncertainty: 26,
    },
    map: { x: 38, y: 26 },
  },
]

export const nearby = [
  {
    id: 'maya',
    name: 'Maya',
    distance: '1 km',
    photo: '/portraits/maya.jpg',
  },
  {
    id: 'zara',
    name: 'Zara',
    distance: '2 km',
    photo: '/portraits/zara.jpg',
  },
  {
    id: 'kai',
    name: 'Kai',
    distance: '3 km',
    photo: '/portraits/kai.jpg',
  },
  {
    id: 'milan',
    name: 'Milan',
    distance: '4 km',
    photo: '/portraits/milan.jpg',
  },
]
